#+TITLE: Fish Shell Configuration
#+AUTHOR: Richard L. Anderson
#+EMAIL: rich.anderson@gmail.com

* Table of Contents :TOC:
- [[#fish-shell-configuration][Fish Shell Configuration]]
- [[#ssh-agent-and-key-management][SSH Agent and Key Management]]
  - [[#ssh-agent][SSH Agent]]
  - [[#unlock-function][Unlock Function]]
  - [[#lock-function][Lock Function]]
- [[#set-environment-variables-for-x-windows-for-wsl][Set Environment Variables for X Windows for WSL]]
- [[#fish-shell-configuration-1][Fish Shell Configuration]]
- [[#set-the-path][Set the Path]]
- [[#aliases-and-functions][Aliases and Functions]]
  - [[#directory-navigation][Directory Navigation]]
  - [[#package-management][Package Management]]
  - [[#network-utility-functions-and-aliases][Network Utility Functions and Aliases]]
  - [[#clipboard-integration][Clipboard Integration]]

* Fish Shell Configuration
The fish shell is a modern command shell similar to bash, but with an array of improved features.  Please see https://fishshell.com/ for a complete list of features and documentation. This is a literate configuration for the fish shell. Please see https://fishshell.com/docs/current/index.html for full documentation.

#+begin_src fish

# ~/.config/fish/config.fish
#
# Configuration file for the fish shell. This is the output from a
# literate configuration file stored in config.org. Please make your
# edits to config.org rather than config.fish.

#+end_src

* SSH Agent and Key Management

Start SSH agent if it hasn't already started.  Export the SSH_AUTH_SOCK and SSH_AGENT_PID environment variables across sessions.  Add the default SSH key to the SSH agent if it hasn't been done so already. Use *unlock* to add the ssh key to the agent. Use *lock* to remove the key from the SSH agent.

** SSH Agent

#+begin_src fish
# Start SSH Agent

if test -z (pgrep ssh-agent)
	eval (ssh-agent -c) > /dev/null
	set -Ux SSH_AUTH_SOCK $SSH_AUTH_SOCK
	set -Ux SSH_AGENT_PID $SSH_AGENT_PID
end

#+end_src

** Unlock Function
Adds keys to the SSH Agent.

#+begin_src fish

function unlock
    if not ssh-add -l > /dev/null
        ssh-add
    else
        echo "SSH key unlocked."
    end
end

#+end_src

** Lock Function
Removes all keys from the SSH Agent.

#+begin_src fish

function lock
    ssh-add -D
end

#+end_src

* Set Environment Variables for X Windows for WSL
WSL2 uses a NAT'd address for the local host. In order for an X Client (program) to connect to the X Server running on the Windows host, you must set the DISPLAY environment variable to the NAT address of the Windows host. The Windows host also provides DNS services to the WSL virtual machine, so the most reliable way to get that information is to pull it from the /etc/resolv.conf file, which is generated by the Windows host on WSL start up. LIBGL_ALWAYS_INDIRECT=1 directs rendering to the GPU for OpenGL applications rather than the X Server.

#+begin_src fish

# Set DISPLAY if running on WSL2
if uname -r | grep -i microsoft &> /dev/null
    set -Ux DISPLAY (cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
    set -Ux LIBGL_ALWAYS_INDIRECT 1
end

#+end_src


* Fish Shell Configuration
The appearance and functionality of the fish shell is controled by a number of functions and environment variables the function below sets the right prompts to the WSL distribution name using the WSL_DISTRO_NAME environment variable.

#+begin_src fish

function fish_right_prompt
    echo $WSL_DISTRO_NAME
end

# Set variable for the OS Version
#
if test /etc/os-release
	set PRETTY_NAME (awk -F '"' '/PRETTY_NAME/ {print $2}' /etc/os-release)
end
#+end_src
* Set the Path
The code below adds common places where local binaries are stored to the PATH if those directories exist.

#+begin_src fish

# Add user specific directories to the PATH.
if test -e $HOME/bin
	set PATH $PATH $HOME/bin
end

if test -e $HOME/.local/bin
	set PATH $PATH $HOME/.local/bin
end

#+end_src

* Aliases and Functions
The code below provides aliases and functions that I find useful for my day to day work.
** Directory Navigation

#+begin_src fish

## Directory Navigation

alias .. "cd .."
alias ... "cd ../.."

#+end_src
** Package Management

#+begin_src fish

## Package Management

function lspkg
    # Lists the installed packages on the system.
    dpkg -l | awk '/^[hi]i/{print $2}'
end


alias apt "sudo apt"
alias aptup "sudo apt update && sudo apt upgrade"

#+end_src
** Network Utility Functions and Aliases

#+begin_src fish

## Network Utility Functions and Aliases
alias ping "sudo ping"

function hostg
    # Runs the host command using Google's DNS server.
    host $argv 8.8.8.8
end

function hostm
    # Runs the host command using Cloudflare's DNS server that filters Malware.
    host $argv 1.1.1.2
end

function mypubip
    # Grabs the machines public IP address from icanhazip.com
    curl icanhazip.com
end
#+end_src

** Clipboard Integration

#+begin_src fish

## Map clip to the Windows Clipboard

if test -e /mnt/c/Windows/system32/clip.exe
	alias clip /mnt/c/Windows/system32/clip.exe
end

#+end_src
